import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@app/providers/Providers";

const MuseoModerno = localFont({
  src: "./fonts/MuseoModerno.ttf",
  variable: "--font-museo-moderno",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`bg-dark-primary antialiased text-balance h-inherit text-white ${MuseoModerno.variable} font-MuseoModerno`}>
        <Providers>
          {children}
        </Providers>
        <SpeedInsights />
      </body>
    </html>
  );
}
