import { ProjectRatingSystemEnumT as PRST } from "@entities/types/enum.types";
import  { TechnologyStackIF, SocialIF, BlogIF } from "@entities/interfaces/additional";
import { TagIF } from "@entities/interfaces/tags.interfaces";
import { ProjectIF } from "@entities/interfaces/project.interfaces";

const _date: Date = new Date("2025-01-01 16:20:09.207");

const stack: TechnologyStackIF[] = [
    {label: "HTML 5", icon: "html"},
    {label: "CSS 3", icon: "css"},
    {label: "SCSS", icon: "scss"},
    {label: "Tailwind CSS", icon: "tailwind"},
    {label: "JavaScript", icon: "js"},
    {label: "TypeScript", icon: "ts"},
    {label: "React", icon: "react"},
    {label: "NextJS", icon: "nextjs"},
    {label: "NestJS", icon: "nestjs"},
    {label: "NodeJS", icon: "nodejs"},
    {label: "Prisma ORM", icon: "prisma"},
    {label: "Graph QL", icon: "graphql"},
    {label: "PostgreSQL", icon: "postgresql"},
    {label: "Laravel", icon: "laravel"},
    {label: "Python", icon: "py"},
    {label: "Flask", icon: "flask"},
    {label: "Git", icon: "git"},
    {label: "Figma", icon: "figma"},
];

const socials: SocialIF[] = [
    {label: "Vkontakte", icon: "vk", href: "https://vk.com/clyoucker"},
    {label: "Telegram", icon: "telegram", href: "https://t.me/Clyoucker"},
    {label: "Twitter", icon: "twitter", href: "#"},
    {label: "Facebook", icon: "facebook", href: "#"},
    {label: "Discord", icon: "discord", href: "#"},
    {label: "YouTube", icon: "youtube", href: "#"},
    {label: "Boosty", icon: "boosty", href: "#"},
    {label: "Git", icon: "git", href: "https://github.com/LiterTeams"},
];

const blogs: BlogIF[] = [
    {
        id: 1,
        title: "Test Title",
        description: "Test Description",
        image: "https://sun9-41.userapi.com/impg/fCz4zghpOVJDGqL9rvd5_Njm_YyeD1XRrCE6VQ/6TAMkzFdH1o.jpg?size=1440x1800&quality=95&sign=c870a33dd305e773a550a7b5a5c4b198&type=album",
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 3,
        title: "Test Title",
        description: "Test Description",
        image: "https://sun1-96.userapi.com/impg/af9YoRcg-AREYKKml1aHAamjP-jhcoFgnllKKg/SOPNTV3LzHU.jpg?size=2560x1650&quality=95&sign=78baf9fea66d6c786caee4b7176a8d7c&type=album",
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 4,
        title: "Test Title",
        description: "Test Description",
        image: "https://sun9-33.userapi.com/impg/XWb6CzljDd7b96WnpiobnPfy2XwhPpwy5eUy2w/Xtye8RgGHfw.jpg?size=1200x848&quality=95&sign=f01e86d8b65ed855b959f8d4d98d5946&type=album",
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 5,
        title: "Test Title",
        description: "Test Description",
        image: "https://sun9-50.userapi.com/impg/82Rnio3H4ANZdJJz181cLQmgosRCN76Ozg60Qg/8dYNYT_CvIY.jpg?size=1080x1578&quality=95&sign=9171fc1051cfed2be990c0590f899587&type=album",
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 6,
        title: "Test Title",
        description: "Test Description",
        image: "https://sun1-13.userapi.com/impg/kW2VKo7EjRwSxGULZjPflH21Earyv5ZOIo0ltw/1AkvUuyzw0o.jpg?size=2560x1807&quality=96&sign=4b8f56e340c5bb8b07bcea28434bf934&type=album",
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 7,
        title: "Test Title",
        description: "Test Description",
        image: "https://sun9-24.userapi.com/impg/UzG2BcY2xW6H5ENzEFk6vSb6eKOE6Wh1M3tsoQ/nwIhr-0FIak.jpg?size=2088x1514&quality=96&sign=345be2a6741a63289820a25a248db30a&type=album",
        created_at: _date,
        updated_at: _date,
    },
];

const tags: TagIF[] = [
    {id: 2, title: "NextJS"},
    {id: 3, title: "NestJS"},
    {id: 4, title: "TypeScript"},
    {id: 5, title: "Tailwind CSS"},
    {id: 6, title: "Prisma"},
    {id: 7, title: "PostgreSQL"},
];

const projects: ProjectIF[] = [
    {
        id: 1,
        title: "Dragon Age",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/d9/b9/c6/d9b9c6935ce4a5025e4fd5ac37b5c3bc.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 2,
        title: "OS Web Argon",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/78/6c/3e/786c3e99c9b9cbfdf93cbfa08c2697dc.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 3,
        title: "Patreon Alternative",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "NC-17",
        image: "https://i.pinimg.com/736x/88/16/c3/8816c30e1832155a652f25d20c19cd69.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 4,
        title: "Argon CRMS",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/3d/96/54/3d96548c8a3d31c0f0e88441c9c6f9de.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 5,
        title: "Yummy Anime 2.0",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "NC-17",
        image: "https://i.pinimg.com/736x/da/22/da/da22da025772aeafee84358fb84f269e.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 6,
        title: "Bite 2.0",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/cc/a2/97/cca2979946d311d86e29766eb598b25d.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 7,
        title: "Electron",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/91/95/4a/91954a4e86ce4ddf06894846246d0702.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 8,
        title: "Discord Alternative",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/0f/6c/b8/0f6cb80e9764bd8e147bfe91483c0aea.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 9,
        title: "EroHub",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "NC-17",
        image: "https://i.pinimg.com/736x/0d/99/d0/0d99d0495f3757182cc7937a3def1bb8.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 10,
        title: "Foxhole Teams",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/e8/42/d9/e842d98c29365966f111a138e88df620.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 11,
        title: "Portfolio - LT | Salfiya",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/ac/96/85/ac9685a23871a89cf79f0430278bb8fe.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 12,
        title: "Portfolio - 乃ﾚﾘﾑｲ ",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "R",
        image: "https://i.pinimg.com/736x/f3/42/10/f342103afd8762ba4f60372026d3102d.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 13,
        title: "Succubus Reborn",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "NC-17",
        image: "https://i.pinimg.com/736x/ae/7f/d5/ae7fd5ceaf1ad6b708988de4cc2b27e8.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 14,
        title: "Monster Hunter",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "NC-17",
        image: "https://i.pinimg.com/736x/b7/f5/18/b7f518b2146c2e7854b784b88c03f308.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
    {
        id: 15,
        title: "Nights of Temptation",
        description: "A web service, the purpose of which is to provide users with a platform for conducting DND games.",
        status: "wip",
        version: "1.5",
        PRS: "NC-17",
        image: "https://i.pinimg.com/736x/f5/81/03/f58103864d6e0218c95ca1afebad2771.jpg",
        tags: tags,
        created_at: _date,
        updated_at: _date,
    },
];

const ratingSystem: Record<PRST, string> = {
    "G": "0+",
    "PG": "6+",
    "PG-13": "14+",
    "R": "16+",
    "NC-17": "18+",
}

export { stack, socials, blogs, projects, ratingSystem }